### ISSUE TITLE
kaminariのpage_entries_infoの文言を日本語化する。

### ISSUE THREAD

**Issue by succi0303** [succi0303/bindr#25]
`page_entries_info`の英語メッセージは以下の通り。

```yaml
page_entries_info:
  one_page:
    display_entries:
      zero: "No %{entry_name} found"
      one: "Displaying <b>1</b> %{entry_name}"
      other: "Displaying <b>all %{count}</b> %{entry_name}"
  more_pages:
    display_entries: "Displaying %{entry_name} <b>%{first}&nbsp;-&nbsp;%{last}</b> of <b>%{total}</b> in total"
```
